### ISSUE TITLE
[Ecowitt] An issue occured while updating sensor values for WH40. Update on 7044:WH40 requires data 

### ISSUE THREAD

**Issue by AlbyZ** [rhockenbury/homebridge-ecowitt-weather-sensors#44]
***

name: Bug Report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

***

**Describe The Bug:**

WH40 - Self Emptying Water gauge does not send valid data-  Recommendation in the Error Message is to restart Homebride to reregister the Sensor, which does not resolve the issue.

Additionally, WS90 returns a Current Ambient Light level over the maximum (set somewhere) of 100,000

**To Reproduce:**

Restart Homebridge and the Error Messages appear every few minutes.  For the Ambient Light Level I have tried the Thresholds at botht he default blank and the current setting of 0.

**Expected behavior:**

During normal Operation that these Errors do not appear in he lo

**Logs:**

[09/12/2024, 16:04:48] [Ecowitt] Setting Rain Rate intensity to None
[09/12/2024, 16:04:48] [Ecowitt] Updating sensor - type: WH51 channel: 1
[09/12/2024, 16:04:48] [Ecowitt] Updating accessory 7044:WH51CH1
[09/12/2024, 16:04:48] [Ecowitt] Updating sensor - type: WH40
[09/12/2024, 16:04:48] [Ecowitt] An issue occured while updating sensor values for WH40. Update on 7044:WH40 requires data rainbatt,rainratein,eventrainin,hourlyrainin,dailyrainin,weeklyrainin,monthlyrainin,yearlyrainin. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 16:05:48] [Ecowitt] Received request for POST /data/report from ::ffff:192.168.1.89
[09/12/2024, 16:05:48] [Ecowitt] Recieved data report, if you are submitting a bug report copy and paste the full data report object 
[Ecowitt] Updating accessory 7044:WS90
[09/12/2024, 16:05:49] [homebridge-ecowitt-weather-sensors] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 113749.993 exceeded maximum of 100000. See https://homebridge.io/w/JtMGR for more info.
[09/12/2024, 16:05:49] [homebridge-ecowitt-weather-sensors] Error: 
    at CurrentAmbientLightLevel.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at CurrentAmbientLightLevel.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2932:14)
    at CurrentAmbientLightLevel.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at LightSensor.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at LightSensor.updateLux (/var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/sensors/LightSensor.ts:62:18)
    at LightSensor.update (/var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/sensors/LightSensor.ts:54:10)
    at WS90.update (/var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/devices/WS90.ts:219:26)
    at EcowittPlatform.updateAccessories (/var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/EcowittPlatform.ts:719:28)
    at EcowittPlatform.onDataReport (/var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/EcowittPlatform.ts:283:10)
    at /var/lib/homebridge/node_modules/homebridge-ecowitt-weather-sensors/src/EcowittPlatform.ts:143:14

**Data Report:**

```

 {
  "PASSKEY": "<deleted>",
  "stationtype": "GW1200C_V1.3.3",
  "runtime": "1015983",
  "heap": "98948",
  "dateutc": "2024-12-09 05:05:47",
  "tempinf": "75.74",
  "humidityin": "40",
  "baromrelin": "28.739",
  "baromabsin": "28.739",
  "tempf": "70.52",
  "humidity": "44",
  "winddir": "107",
  "windspeedmph": "2.68",
  "windgustmph": "6.71",
  "maxdailygust": "13.42",
  "solarradiation": "897.79",
  "uv": "8",
  "rainratein": "0.000",
  "eventrainin": "0.000",
  "hourlyrainin": "0.000",
  "dailyrainin": "0.000",
  "weeklyrainin": "0.000",
  "monthlyrainin": "0.764",
  "yearlyrainin": "3.945",
  "totalrainin": "3.945",
  "rrain_piezo": "0.000",
  "erain_piezo": "0.000",
  "hrain_piezo": "0.000",
  "drain_piezo": "0.000",
  "wrain_piezo": "0.000",
  "mrain_piezo": "0.780",
  "yrain_piezo": "0.780",
  "srain_piezo": "0",
  "ws90cap_volt": "5.4",
  "ws90_ver": "144",
  "soilmoisture1": "38",
  "soilad1": "171",
  "wh40batt": "1.5",
  "soilbatt1": "1.6",
  "wh90batt": "3.12",
  "freq": "433M",
  "model": "GW1200C",
  "interval": "60"
}
```

**Plugin Config:**

"name": "Ecowitt",
    "baseStation": {
        "mac": "<deleted>",
        "port": 8085,
        "path": "/data/report"
    },
    "additional": {
        "staticNames": "false",
        "validateMac": "true",
        "luxFactor": 126.7,
        "acceptAnyPath": "false",
        "validateTimestamp": "true",
        "removeStaleDevices": "true"
    },
    "thresholds": {
        "rainRate": 0,
        "rainEventTotal": 0,
        "rainHourlyTotal": 0,
        "rainDailyTotal": 0,
        "rainWeeklyTotal": 0,
        "rainMonthlyTotal": 0,
        "rainYearlyTotal": 0
    },
    "units": {
        "wind": "kph",
        "rain": "mm",
        "distance": "km",
        "temperature": "ce"
    },
    "platform": "Ecowitt"
}

**Screenshots:**

![EcoWitt Error](https://github.com/user-attachments/assets/542cb75d-92fc-464c-8d27-471b5b16bcc4)

**Environment:**

* **Plugin Version**:v2.5.1
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.18.1
* **NPM Version**: 10.8.2
* **Operating System**: Raspberry Pi Model B Plus Rev 1.2 - image_2024-11-29-Homebridge-bookworm-32bit

**Comment by rhockenbury** [comment]
Thank you @AlbyZ for reporting this.  I've taken a quick look and both issues look like they are bugs in the plugin.  I'll take some time to address.  Thanks.

**Comment by Tomhodgson** [comment]
I am seeing the same here with the same version of the plugin and Homebridge. I am forwarding the data through FOSHKPlugin as I also use CumulusMX with my weather station. 

This is therefore reporting zero or not detected values for any of the detected WS90 sensors connected to my HP2564 Gateway.

[09/12/2024, 21:42:56] [Ecowitt] Note that accessory HP2564 does not currently use and/or display the following data: baromrelin,baromabsin
[09/12/2024, 21:42:56] [Ecowitt] Restoring existing accessory from cache - type: WS90, uuid: ad2c3197-ebaf-459f-8560-1c938800b5a2
[09/12/2024, 21:42:56] [Ecowitt] Note that accessory WS90 does not currently use and/or display the following data: ws90cap_volt,ws90_ver
[09/12/2024, 21:42:56] [Ecowitt] There was unused data from data report rainratein,eventrainin,hourlyrainin,dailyrainin,weeklyrainin,monthlyrainin,yearlyrainin,gain10_piezo,gain20_piezo,gain30_piezo,gain40_piezo,gain50_piezo. This indicates that a sensor may not have been successfully discovered. Try restarting Homebridge so that the plugin re-registers devices from the data report
[09/12/2024, 21:42:56] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:43:19] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:43:42] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:44:03] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:44:24] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:44:45] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:45:10] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:45:34] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:45:55] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:46:16] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:46:38] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:46:59] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ
[09/12/2024, 21:47:20] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo. Please file a bug report if needed at https://bit.ly/3yklrWZ

**Comment by Tomhodgson** [comment]
I rolled back to 2.5.1 and the issue was still present. 
Then rolled back to 2.4.1 and the issue was still present. 
Rolled back to 2.4.0 Beta when the WS90 support was added and the issue still occurred with the following messages:

[09/12/2024, 22:06:59] [Ecowitt] Note that accessory WS90 does not currently display the following data: ws90cap_volt,ws90_ver
[09/12/2024, 22:06:59] [Ecowitt] There was unused data from data report rainratein,eventrainin,hourlyrainin,dailyrainin,weeklyrainin,monthlyrainin,yearlyrainin,gain10_piezo,gain20_piezo,gain30_piezo,gain40_piezo,gain50_piezo. This indicates that a sensor may not have been successfully discovered. Try restarting Homebridge so that the plugin re-registers devices from the data report
[09/12/2024, 22:06:59] [Ecowitt] An issue occured while updating sensor values for WS90.

**Comment by rhockenbury** [comment]
Hi @Tomhodgson.  Would you be able to provide a copy/paste of your data report?  Instructions for obtaining that can be found [here](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/wiki/Submitting-Data-Report).

**Comment by Tomhodgson** [comment]
Hi @rhockenbury sure thing here you are:

[09/12/2024, 23:50:01] [Ecowitt] Recieved data report, if you are submitting a bug report copy and paste the full data report object 
 {
  "PASSKEY": "REMOVED",
  "stationtype": "EasyWeatherPro_V5.1.7",
  "runtime": "2437708",
  "heap": "25328",
  "dateutc": "2024-12-09 23:50:01",
  "tempinf": "66.7",
  "humidityin": "54",
  "baromrelin": "29.976",
  "baromabsin": "29.976",
  "tempf": "41.4",
  "humidity": "79",
  "winddir": "234",
  "windspeedmph": "2.68",
  "windgustmph": "10.74",
  "maxdailygust": "23.93",
  "solarradiation": "0.00",
  "uv": "0",
  "rainratein": "0.000",
  "eventrainin": "2.150",
  "hourlyrainin": "0.000",
  "dailyrainin": "0.165",
  "weeklyrainin": "0.705",
  "monthlyrainin": "2.441",
  "yearlyrainin": "4.004",
  "ws90cap_volt": "2.4",
  "ws90_ver": "147",
  "gain10_piezo": "1.00",
  "gain20_piezo": "1.00",
  "gain30_piezo": "1.00",
  "gain40_piezo": "1.00",
  "gain50_piezo": "1.00",
  "wh90batt": "2.96",
  "freq": "868M",
  "model": "HP2564AE_Pro_V1.9.8",
  "interval": "20",
  "isintvl": "21",
  "isintvl10": "22",
  "dewptf": "35.3",
  "windchillf": "41.4",
  "feelslikef": "41.4",
  "heatindexf": "39.0",
  "windspdmph_avg10m": "2.9",
  "winddir_avg10m": "328",
  "windgustmph_max10m": "12.1",
  "windrun": "10.94",
  "brightness": "0.0",
  "sunhours": "0.0",
  "sunshine": "0",
  "srsum": "0.0",
  "ptrend1": "-1",
  "pchange1": "-0.003"
}

**Comment by Tomhodgson** [comment]
@rhockenbury I did also change FOSHKPlugin to forward the data type as Ecowitt Format (EW) rather than RAWEW which it was at before and I now get the error messages as follows instead:
[09/12/2024, 23:49:19] [Ecowitt] An issue occured while updating sensor values for WS90. Update on 7936:WS90 requires data wh90batt,tempf,humidity,solarradiation,uv,winddir,windspeedmph,windgustmph,maxdailygust,rrain_piezo,erain_piezo,hrain_piezo,drain_piezo,wrain_piezo,mrain_piezo,yrain_piezo.

**Comment by rhockenbury** [comment]
Hi @Tomhodgson. It looks like the data report is missing the piezo rain values - which is expected for the WS90 b/c it has the piezo rain gauge.  Here's an example of a data report with all expected WS90 values - https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/blob/master/tests/synthetic/data/hp2564_ws90.json#L18-L24.  

Is it possible that the FOSHKPlugin is remapping the rain values?  Would you be able to share the data report that's coming directly from your Ecowitt base station before it's processed by the FOSHKPlugin?

**Comment by Tomhodgson** [comment]
@rhockenbury I pointed the Ecowitt straight at the homebridge Pi and actually that has worked just fine. Apologies I really should have thought to try that before, it looks like the FOSHKPlugin is the issue then. I will have to look for a workaround then to see what is happening but as far as I know it should be sending the data straight through just fine as RAWEW or EW type

**Comment by Tomhodgson** [comment]
@rhockenbury I figured it out. In the FOSHK config file I had the value WS90_CONVERT = True in the weatherstation configuration which was outputting the wrong strings. I have changed this back to False instead of True and it is working fine now

**Comment by rhockenbury** [comment]
Hi @Tomhodgson, that's great to hear.  Would you be willing to share your FOSHK config file?  It might be useful for others using FOSHK with the Ecowitt plugin to have that as reference. 

I'll leave this issue open as I still need to resolve the two issues that @AlbyZ brought up.  I should have the fix for those published in early January.

**Comment by rhockenbury** [comment]
Hi @AlbyZ.  Please try out v2.6.0 for a fix for the issues you mentioned, and let me know if you hit any more issues.

And if you feel you are getting value from this plugin, please consider giving this repo a star.

**Comment by AlbyZ** [comment]
Apologies for the delay, only just came back from a holiday.  Looks like the problem has gone away.  Thanks heaps!
